# Generated by Django 6.1 on 2026-08-30 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='路径标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(choices=[('main', '主空间（信息收录）'), ('guide', '攻略空间（预留）'), ('user', '用户空间（预留）'), ('meta', '站务空间')], default='main', max_length=20, verbose_name='命名空间')),
                ('slug', models.SlugField(max_length=120, verbose_name='路径标识')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content_md', models.TextField(blank=True, verbose_name='Markdown 正文')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='published', max_length=20, verbose_name='状态')),
                ('is_protected', models.BooleanField(default=False, verbose_name='受保护')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '词条',
                'verbose_name_plural': '词条',
                'ordering': ['-updated_at'],
                'unique_together': {('namespace', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_md', models.TextField(verbose_name='Markdown 正文')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='编辑摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修订时间')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='编辑者')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wiki.wikipage', verbose_name='词条')),
            ],
            options={
                'verbose_name': '词条修订',
                'verbose_name_plural': '词条修订',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wiki.category', verbose_name='分类')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='wiki.wikipage', verbose_name='词条')),
            ],
            options={
                'verbose_name': '词条分类',
                'verbose_name_plural': '词条分类',
                'unique_together': {('page', 'category')},
            },
        ),
    ]
