# Generated by Django 6.1 on 2026-08-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('link_url', models.URLField(verbose_name='跳转链接')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='简介')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '精华推荐',
                'verbose_name_plural': '精华推荐',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image_url', models.URLField(help_text='可填站外图片地址或站内 /static/ 路径', verbose_name='图片链接')),
                ('link_url', models.URLField(blank=True, help_text='点击图片后跳转的地址，可留空', verbose_name='跳转链接')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfficialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.URLField(verbose_name='链接')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '官方信息链接',
                'verbose_name_plural': '官方信息链接',
                'ordering': ['order', 'id'],
            },
        ),
    ]
