# Generated by Django 6.1 on 2026-08-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_home_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.URLField(blank=True, help_text='留空则使用纯色背景；可填图床图片地址', verbose_name='背景图片链接')),
                ('background_color', models.CharField(default='#12141a', help_text='十六进制颜色，如 #12141a', max_length=20, verbose_name='背景颜色')),
                ('background_size', models.CharField(choices=[('cover', '铺满（cover）'), ('contain', '完整显示（contain）'), ('repeat', '原尺寸重复')], default='cover', max_length=20, verbose_name='背景尺寸')),
                ('background_position', models.CharField(default='center center', help_text='如 center center / top left', max_length=30, verbose_name='背景位置')),
            ],
            options={
                'verbose_name': '站点外观',
                'verbose_name_plural': '站点外观',
            },
        ),
    ]
