# Generated by Django 6.1 on 2026-08-30 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_site_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteappearance',
            name='overlay_opacity',
            field=models.FloatField(default=0.55, help_text='0 = 不遮罩，1 = 全黑遮罩；背景图存在时生效', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='背景遮罩不透明度'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='site_name',
            field=models.CharField(default='源神小窝', max_length=50, verbose_name='站点名称'),
        ),
    ]
