# Generated by Django 6.1 on 2026-08-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteappearance_overlay_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteappearance',
            name='accent_color',
            field=models.CharField(default='#c9a86a', max_length=20, verbose_name='主题色'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='border_color',
            field=models.CharField(default='#2c3140', max_length=20, verbose_name='边框色'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='logo_height',
            field=models.PositiveIntegerField(default=32, verbose_name='Logo 高度（px）'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='logo_image',
            field=models.URLField(blank=True, help_text='留空则显示站点名称文字；可填图床 PNG/SVG 地址', verbose_name='Logo 图片链接'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='muted_color',
            field=models.CharField(default='#8b8fa0', max_length=20, verbose_name='次要文字色'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='panel_color',
            field=models.CharField(default='#1b1e27', max_length=20, verbose_name='面板色'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='site_slogan',
            field=models.CharField(blank=True, default='《源初之结》（NODUSFALL）粉丝资料站 —— 收录设定、视频与资讯', max_length=120, verbose_name='站点标语'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='text_color',
            field=models.CharField(default='#e6e3da', max_length=20, verbose_name='文字色'),
        ),
    ]
