# Generated by Django 6.1 on 2026-08-31 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteappearance_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteappearance',
            name='background_image_file',
            field=models.ImageField(blank=True, help_text='直接上传 jpg/png 图片；与上方链接二选一', upload_to='backgrounds/', validators=[django.core.validators.validate_image_file_extension], verbose_name='背景图片文件（jpg/png）'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='theme',
            field=models.CharField(choices=[('custom', '自定义（使用下方颜色）'), ('dark-gold', '暗夜鎏金'), ('ocean', '深海蓝'), ('violet', '暮紫'), ('forest', '森林绿'), ('crimson', '绯红'), ('sunset', '落日橙')], default='custom', max_length=20, verbose_name='主题预设'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='background_image',
            field=models.URLField(blank=True, help_text='图片链接与下方文件二选一；留空则使用纯色背景', verbose_name='背景图片链接'),
        ),
    ]
