# Generated by Django 6.1 on 2026-08-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteappearance_background_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteappearance',
            name='logo_height',
            field=models.PositiveIntegerField(default=40, verbose_name='Logo 高度（px）'),
        ),
    ]
