# Generated by Django 6.1 on 2026-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_update_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteappearance',
            name='site_slogan',
            field=models.CharField(blank=True, default='诸神入刃，斩尽死结', max_length=120, verbose_name='站点标语'),
        ),
    ]
