# Generated by Django 6.1 on 2026-08-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_update_modern_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteappearance',
            name='accent_color',
            field=models.CharField(default='#6366f1', max_length=20, verbose_name='主题色'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='background_color',
            field=models.CharField(default='#0f1117', help_text='十六进制颜色，如 #0f1117', max_length=20, verbose_name='背景颜色'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='border_color',
            field=models.CharField(default='#262a38', max_length=20, verbose_name='边框色'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='muted_color',
            field=models.CharField(default='#9aa0b0', max_length=20, verbose_name='次要文字色'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='panel_color',
            field=models.CharField(default='#14161f', max_length=20, verbose_name='面板色'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='text_color',
            field=models.CharField(default='#e8eaf2', max_length=20, verbose_name='文字色'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='theme',
            field=models.CharField(choices=[('custom', '自定义（使用下方颜色）'), ('dark-gold', '深空靛蓝'), ('ocean', '海蓝'), ('violet', '紫罗兰'), ('forest', '薄荷绿'), ('crimson', '珊瑚红'), ('sunset', '琥珀橙')], default='custom', max_length=20, verbose_name='主题预设'),
        ),
    ]
