# Generated by Django 6.1 on 2026-08-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_revert_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteappearance',
            name='site_slogan',
            field=models.CharField(blank=True, default='《源初之结》（NODUSFALL）粉丝资料站 —— 收录设定、视频与资讯', max_length=120, verbose_name='站点标语'),
        ),
    ]
