# Generated by Django 6.1 on 2026-08-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='版块名称')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='路径标识')),
                ('description', models.TextField(blank=True, verbose_name='版块说明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '论坛版块',
                'verbose_name_plural': '论坛版块',
                'ordering': ['order', 'id'],
            },
        ),
    ]
