# Generated by Django 6.1 on 2026-08-30 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('bilibili', '哔哩哔哩'), ('youtube', 'YouTube')], max_length=20, verbose_name='平台')),
                ('video_id', models.CharField(max_length=80, verbose_name='视频 ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('cover_url', models.URLField(blank=True, verbose_name='封面链接')),
                ('source_url', models.URLField(verbose_name='来源链接')),
                ('category', models.CharField(choices=[('official_pv', '官方 PV / 预告'), ('gameplay', '实机演示'), ('preview', '试玩评测'), ('interview', '开发组采访'), ('fanwork', '二创作品')], default='official_pv', max_length=20, verbose_name='分类')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='UP 主/频道')),
                ('language', models.CharField(default='zh', max_length=20, verbose_name='语言')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='发布时间')),
                ('license_note', models.CharField(blank=True, max_length=200, verbose_name='授权备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='收录人')),
                ('pages', models.ManyToManyField(blank=True, related_name='videos', to='wiki.wikipage', verbose_name='关联词条')),
            ],
            options={
                'verbose_name': '视频条目',
                'verbose_name_plural': '视频条目',
                'ordering': ['-created_at'],
            },
        ),
    ]
